# Generated by Django 5.0.6 on 2026-08-24 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='postponed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('lanh_dao', 'Ban Lãnh đạo'), ('van_thu', 'Văn thư Ủy ban'), ('quan_tri', 'Quản trị hệ thống (SuperAdmin)'), ('phong_ban', 'Văn thư Văn phòng / Phòng ban'), ('thanh_vien', 'Cán bộ, công chức')], max_length=20),
        ),
    ]
