# Generated by Django 5.2.17 on 2026-08-24 13:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meetingfile',
            name='storage_path',
        ),
        migrations.AddField(
            model_name='meeting',
            name='is_draft',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='meeting',
            name='minutes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='meetingfile',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='meeting_files/%Y/%m/'),
        ),
        migrations.CreateModel(
            name='ConflictAcknowledgement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('meeting_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.meeting')),
                ('meeting_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.meeting')),
            ],
            options={
                'db_table': 'conflict_acknowledgements',
                'unique_together': {('meeting_a', 'meeting_b')},
            },
        ),
    ]
