# Generated by Django 5.2.17 on 2026-08-25 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_meetingfile_storage_path_meeting_is_draft_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='can_manage_rooms',
            field=models.BooleanField(default=False, help_text='Duoc them/sua/xoa phong hop du khong phai quan_tri (vd. can bo phu trach ha tang/server).'),
        ),
    ]
